/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Genre = { 'Action' : null } |
  { 'Romance' : null } |
  { 'Thriller' : null };
export type Hash = string;
export type PremiumPlan = { 'Monthly' : null } |
  { 'Yearly' : null };
export interface PremiumRequest {
  'id' : bigint,
  'status' : PremiumRequestStatus,
  'userId' : Principal,
  'plan' : PremiumPlan,
  'submittedAt' : Time,
  'reviewedAt' : [] | [Time],
  'utrId' : string,
}
export type PremiumRequestStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export type Time = bigint;
export interface User {
  'isPremium' : boolean,
  'mobileNumber' : string,
  'premiumExpiresAt' : [] | [Time],
  'passwordHash' : Hash,
  'lastName' : string,
  'firstName' : string,
}
export interface UserProfile {
  'isPremium' : boolean,
  'mobileNumber' : string,
  'premiumExpiresAt' : [] | [Time],
  'lastName' : string,
  'firstName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : bigint,
  'title' : string,
  'thumbnailUrl' : string,
  'createdAt' : Time,
  'description' : string,
  'isPremiumOnly' : boolean,
  'genre' : Genre,
  'durationSeconds' : bigint,
  'videoUrl' : string,
}
export interface WatchProgress {
  'lastWatchedAt' : Time,
  'completed' : boolean,
  'watchedSeconds' : bigint,
  'videoId' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContinueWatching' : ActorMethod<[], Array<WatchProgress>>,
  'getPendingPremiumRequests' : ActorMethod<[], Array<PremiumRequest>>,
  'getPremiumRequests' : ActorMethod<[], Array<PremiumRequest>>,
  'getUser' : ActorMethod<[string], [] | [User]>,
  'getUserPremiumStatus' : ActorMethod<[], [boolean, [] | [Time]]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideoById' : ActorMethod<[bigint], [] | [Video]>,
  'getWatchProgress' : ActorMethod<[bigint], [] | [WatchProgress]>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllVideos' : ActorMethod<[], Array<Video>>,
  'listVideosByGenre' : ActorMethod<[Genre], Array<Video>>,
  'login' : ActorMethod<[string, Hash], boolean>,
  'recordProgress' : ActorMethod<[bigint, bigint], boolean>,
  'register' : ActorMethod<[string, string, string, Hash], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitPremiumRequest' : ActorMethod<[PremiumPlan, string], bigint>,
  'verifyPremiumRequest' : ActorMethod<[bigint, boolean], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];