/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'isPremium' : IDL.Bool,
  'mobileNumber' : IDL.Text,
  'premiumExpiresAt' : IDL.Opt(Time),
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const WatchProgress = IDL.Record({
  'lastWatchedAt' : Time,
  'completed' : IDL.Bool,
  'watchedSeconds' : IDL.Nat,
  'videoId' : IDL.Nat,
});
export const PremiumRequestStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const PremiumPlan = IDL.Variant({
  'Monthly' : IDL.Null,
  'Yearly' : IDL.Null,
});
export const PremiumRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : PremiumRequestStatus,
  'userId' : IDL.Principal,
  'plan' : PremiumPlan,
  'submittedAt' : Time,
  'reviewedAt' : IDL.Opt(Time),
  'utrId' : IDL.Text,
});
export const Hash = IDL.Text;
export const User = IDL.Record({
  'isPremium' : IDL.Bool,
  'mobileNumber' : IDL.Text,
  'premiumExpiresAt' : IDL.Opt(Time),
  'passwordHash' : Hash,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const Genre = IDL.Variant({
  'Action' : IDL.Null,
  'Romance' : IDL.Null,
  'Thriller' : IDL.Null,
});
export const Video = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'isPremiumOnly' : IDL.Bool,
  'genre' : Genre,
  'durationSeconds' : IDL.Nat,
  'videoUrl' : IDL.Text,
});
export const UserRecord = IDL.Record({
  'principal' : IDL.Principal,
  'firstName' : IDL.Text,
  'lastName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'isPremium' : IDL.Bool,
  'premiumExpiresAt' : IDL.Opt(Time),
});
export const PaymentSettings = IDL.Record({
  'upiId' : IDL.Text,
  'qrCodeUrl' : IDL.Text,
});
export const HelpDeskRequest = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'problem' : IDL.Text,
  'submittedAt' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContinueWatching' : IDL.Func([], [IDL.Vec(WatchProgress)], ['query']),
  'getPendingPremiumRequests' : IDL.Func([], [IDL.Vec(PremiumRequest)], ['query']),
  'getPremiumRequests' : IDL.Func([], [IDL.Vec(PremiumRequest)], ['query']),
  'getUser' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
  'getUserPremiumStatus' : IDL.Func([], [IDL.Bool, IDL.Opt(Time)], ['query']),
  'getUserPremiumPlan' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
  'getVideoById' : IDL.Func([IDL.Nat], [IDL.Opt(Video)], ['query']),
  'getWatchProgress' : IDL.Func([IDL.Nat], [IDL.Opt(WatchProgress)], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'listVideosByGenre' : IDL.Func([Genre], [IDL.Vec(Video)], ['query']),
  'login' : IDL.Func([IDL.Text, Hash], [IDL.Bool], ['query']),
  'recordProgress' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Hash], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitPremiumRequest' : IDL.Func([PremiumPlan, IDL.Text], [IDL.Nat], []),
  'verifyPremiumRequest' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
  'getPaymentSettings' : IDL.Func([], [PaymentSettings], ['query']),
  'updatePaymentSettings' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'activateAdminWithCode' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserRecord)], ['query']),
  'addVideo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, Genre, IDL.Nat, IDL.Bool], [IDL.Nat], []),
  'deleteVideo' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'submitHelpDeskRequest' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'listHelpDeskRequests' : IDL.Func([], [IDL.Vec(HelpDeskRequest)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'isPremium' : IDL.Bool,
    'mobileNumber' : IDL.Text,
    'premiumExpiresAt' : IDL.Opt(Time),
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const WatchProgress = IDL.Record({
    'lastWatchedAt' : Time,
    'completed' : IDL.Bool,
    'watchedSeconds' : IDL.Nat,
    'videoId' : IDL.Nat,
  });
  const PremiumRequestStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const PremiumPlan = IDL.Variant({
    'Monthly' : IDL.Null,
    'Yearly' : IDL.Null,
  });
  const PremiumRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : PremiumRequestStatus,
    'userId' : IDL.Principal,
    'plan' : PremiumPlan,
    'submittedAt' : Time,
    'reviewedAt' : IDL.Opt(Time),
    'utrId' : IDL.Text,
  });
  const Hash = IDL.Text;
  const User = IDL.Record({
    'isPremium' : IDL.Bool,
    'mobileNumber' : IDL.Text,
    'premiumExpiresAt' : IDL.Opt(Time),
    'passwordHash' : Hash,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const Genre = IDL.Variant({
    'Action' : IDL.Null,
    'Romance' : IDL.Null,
    'Thriller' : IDL.Null,
  });
  const Video = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'isPremiumOnly' : IDL.Bool,
    'genre' : Genre,
    'durationSeconds' : IDL.Nat,
    'videoUrl' : IDL.Text,
  });
  const UserRecord = IDL.Record({
    'principal' : IDL.Principal,
    'firstName' : IDL.Text,
    'lastName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'isPremium' : IDL.Bool,
    'premiumExpiresAt' : IDL.Opt(Time),
  });
  const PaymentSettings = IDL.Record({
    'upiId' : IDL.Text,
    'qrCodeUrl' : IDL.Text,
  });
  const HelpDeskRequest = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'problem' : IDL.Text,
    'submittedAt' : Time,
  });

  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContinueWatching' : IDL.Func([], [IDL.Vec(WatchProgress)], ['query']),
    'getPendingPremiumRequests' : IDL.Func([], [IDL.Vec(PremiumRequest)], ['query']),
    'getPremiumRequests' : IDL.Func([], [IDL.Vec(PremiumRequest)], ['query']),
    'getUser' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
    'getUserPremiumStatus' : IDL.Func([], [IDL.Bool, IDL.Opt(Time)], ['query']),
    'getUserPremiumPlan' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
    'getVideoById' : IDL.Func([IDL.Nat], [IDL.Opt(Video)], ['query']),
    'getWatchProgress' : IDL.Func([IDL.Nat], [IDL.Opt(WatchProgress)], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'listVideosByGenre' : IDL.Func([Genre], [IDL.Vec(Video)], ['query']),
    'login' : IDL.Func([IDL.Text, Hash], [IDL.Bool], ['query']),
    'recordProgress' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Hash], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitPremiumRequest' : IDL.Func([PremiumPlan, IDL.Text], [IDL.Nat], []),
    'verifyPremiumRequest' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
    'getPaymentSettings' : IDL.Func([], [PaymentSettings], ['query']),
    'updatePaymentSettings' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'activateAdminWithCode' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserRecord)], ['query']),
    'addVideo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, Genre, IDL.Nat, IDL.Bool], [IDL.Nat], []),
    'deleteVideo' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'submitHelpDeskRequest' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'listHelpDeskRequests' : IDL.Func([], [IDL.Vec(HelpDeskRequest)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };