/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Video {
    id: bigint;
    title: string;
    thumbnailUrl: string;
    createdAt: Time;
    description: string;
    isPremiumOnly: boolean;
    genre: Genre;
    durationSeconds: bigint;
    videoUrl: string;
}
export type Time = bigint;
export interface WatchProgress {
    lastWatchedAt: Time;
    completed: boolean;
    watchedSeconds: bigint;
    videoId: bigint;
}
export interface User {
    isPremium: boolean;
    mobileNumber: string;
    premiumExpiresAt?: Time;
    passwordHash: Hash;
    lastName: string;
    firstName: string;
}
export interface PremiumRequest {
    id: bigint;
    status: PremiumRequestStatus;
    userId: Principal;
    plan: PremiumPlan;
    submittedAt: Time;
    reviewedAt?: Time;
    utrId: string;
}
export type Hash = string;
export interface UserProfile {
    isPremium: boolean;
    mobileNumber: string;
    premiumExpiresAt?: Time;
    lastName: string;
    firstName: string;
}
export enum Genre {
    Action = "Action",
    Romance = "Romance",
    Thriller = "Thriller"
}
export enum PremiumPlan {
    Monthly = "Monthly",
    Yearly = "Yearly"
}
export enum PremiumRequestStatus {
    Approved = "Approved",
    Rejected = "Rejected",
    Pending = "Pending"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContinueWatching(): Promise<Array<WatchProgress>>;
    getPendingPremiumRequests(): Promise<Array<PremiumRequest>>;
    getPremiumRequests(): Promise<Array<PremiumRequest>>;
    getUser(mobileNumber: string): Promise<User | null>;
    getUserPremiumStatus(): Promise<[boolean, Time | null]>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVideoById(id: bigint): Promise<Video | null>;
    getWatchProgress(videoId: bigint): Promise<WatchProgress | null>;
    isAdmin(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    listAllVideos(): Promise<Array<Video>>;
    listVideosByGenre(genre: Genre): Promise<Array<Video>>;
    login(mobileNumber: string, passwordHash: Hash): Promise<boolean>;
    recordProgress(videoId: bigint, watchedSeconds: bigint): Promise<boolean>;
    register(firstName: string, lastName: string, mobileNumber: string, passwordHash: Hash): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitPremiumRequest(plan: PremiumPlan, utrId: string): Promise<bigint>;
    verifyPremiumRequest(requestId: bigint, approve: boolean): Promise<boolean>;
}
import type { Genre as _Genre, Hash as _Hash, PremiumPlan as _PremiumPlan, PremiumRequest as _PremiumRequest, PremiumRequestStatus as _PremiumRequestStatus, Time as _Time, User as _User, UserProfile as _UserProfile, UserRole as _UserRole, Video as _Video, WatchProgress as _WatchProgress } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContinueWatching(): Promise<Array<WatchProgress>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContinueWatching();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContinueWatching();
            return result;
        }
    }
    async getPendingPremiumRequests(): Promise<Array<PremiumRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingPremiumRequests();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingPremiumRequests();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPremiumRequests(): Promise<Array<PremiumRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPremiumRequests();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPremiumRequests();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(arg0: string): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPremiumStatus(): Promise<[boolean, Time | null]> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPremiumStatus();
                return [
                    result[0],
                    from_candid_opt_n6(this._uploadFile, this._downloadFile, result[1])
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPremiumStatus();
            return [
                result[0],
                from_candid_opt_n6(this._uploadFile, this._downloadFile, result[1])
            ];
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoById(arg0: bigint): Promise<Video | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoById(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoById(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWatchProgress(arg0: bigint): Promise<WatchProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWatchProgress(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWatchProgress(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllVideos(): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllVideos();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllVideos();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listVideosByGenre(arg0: Genre): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVideosByGenre(to_candid_Genre_n26(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVideosByGenre(to_candid_Genre_n26(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async login(arg0: string, arg1: Hash): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return result;
        }
    }
    async recordProgress(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.recordProgress(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordProgress(arg0, arg1);
            return result;
        }
    }
    async register(arg0: string, arg1: string, arg2: string, arg3: Hash): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitPremiumRequest(arg0: PremiumPlan, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPremiumRequest(to_candid_PremiumPlan_n30(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPremiumRequest(to_candid_PremiumPlan_n30(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async verifyPremiumRequest(arg0: bigint, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyPremiumRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyPremiumRequest(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Genre_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Genre): Genre {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_PremiumPlan_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PremiumPlan): PremiumPlan {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_PremiumRequestStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PremiumRequestStatus): PremiumRequestStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_PremiumRequest_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PremiumRequest): PremiumRequest {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_User_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Video_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Video): Video {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Video]): Video | null {
    return value.length === 0 ? null : from_candid_Video_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WatchProgress]): WatchProgress | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _PremiumRequestStatus;
    userId: Principal;
    plan: _PremiumPlan;
    submittedAt: _Time;
    reviewedAt: [] | [_Time];
    utrId: string;
}): {
    id: bigint;
    status: PremiumRequestStatus;
    userId: Principal;
    plan: PremiumPlan;
    submittedAt: Time;
    reviewedAt?: Time;
    utrId: string;
} {
    return {
        id: value.id,
        status: from_candid_PremiumRequestStatus_n12(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        plan: from_candid_PremiumPlan_n14(_uploadFile, _downloadFile, value.plan),
        submittedAt: value.submittedAt,
        reviewedAt: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.reviewedAt)),
        utrId: value.utrId
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isPremium: boolean;
    mobileNumber: string;
    premiumExpiresAt: [] | [_Time];
    passwordHash: _Hash;
    lastName: string;
    firstName: string;
}): {
    isPremium: boolean;
    mobileNumber: string;
    premiumExpiresAt?: Time;
    passwordHash: Hash;
    lastName: string;
    firstName: string;
} {
    return {
        isPremium: value.isPremium,
        mobileNumber: value.mobileNumber,
        premiumExpiresAt: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.premiumExpiresAt)),
        passwordHash: value.passwordHash,
        lastName: value.lastName,
        firstName: value.firstName
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    thumbnailUrl: string;
    createdAt: _Time;
    description: string;
    isPremiumOnly: boolean;
    genre: _Genre;
    durationSeconds: bigint;
    videoUrl: string;
}): {
    id: bigint;
    title: string;
    thumbnailUrl: string;
    createdAt: Time;
    description: string;
    isPremiumOnly: boolean;
    genre: Genre;
    durationSeconds: bigint;
    videoUrl: string;
} {
    return {
        id: value.id,
        title: value.title,
        thumbnailUrl: value.thumbnailUrl,
        createdAt: value.createdAt,
        description: value.description,
        isPremiumOnly: value.isPremiumOnly,
        genre: from_candid_Genre_n22(_uploadFile, _downloadFile, value.genre),
        durationSeconds: value.durationSeconds,
        videoUrl: value.videoUrl
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isPremium: boolean;
    mobileNumber: string;
    premiumExpiresAt: [] | [_Time];
    lastName: string;
    firstName: string;
}): {
    isPremium: boolean;
    mobileNumber: string;
    premiumExpiresAt?: Time;
    lastName: string;
    firstName: string;
} {
    return {
        isPremium: value.isPremium,
        mobileNumber: value.mobileNumber,
        premiumExpiresAt: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.premiumExpiresAt)),
        lastName: value.lastName,
        firstName: value.firstName
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Approved: null;
} | {
    Rejected: null;
} | {
    Pending: null;
}): PremiumRequestStatus {
    return "Approved" in value ? PremiumRequestStatus.Approved : "Rejected" in value ? PremiumRequestStatus.Rejected : "Pending" in value ? PremiumRequestStatus.Pending : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Monthly: null;
} | {
    Yearly: null;
}): PremiumPlan {
    return "Monthly" in value ? PremiumPlan.Monthly : "Yearly" in value ? PremiumPlan.Yearly : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Action: null;
} | {
    Romance: null;
} | {
    Thriller: null;
}): Genre {
    return "Action" in value ? Genre.Action : "Romance" in value ? Genre.Romance : "Thriller" in value ? Genre.Thriller : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Video>): Array<Video> {
    return value.map((x)=>from_candid_Video_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PremiumRequest>): Array<PremiumRequest> {
    return value.map((x)=>from_candid_PremiumRequest_n10(_uploadFile, _downloadFile, x));
}
function to_candid_Genre_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Genre): _Genre {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_PremiumPlan_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PremiumPlan): _PremiumPlan {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isPremium: boolean;
    mobileNumber: string;
    premiumExpiresAt?: Time;
    lastName: string;
    firstName: string;
}): {
    isPremium: boolean;
    mobileNumber: string;
    premiumExpiresAt: [] | [_Time];
    lastName: string;
    firstName: string;
} {
    return {
        isPremium: value.isPremium,
        mobileNumber: value.mobileNumber,
        premiumExpiresAt: value.premiumExpiresAt ? candid_some(value.premiumExpiresAt) : candid_none(),
        lastName: value.lastName,
        firstName: value.firstName
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Genre): {
    Action: null;
} | {
    Romance: null;
} | {
    Thriller: null;
} {
    return value == Genre.Action ? {
        Action: null
    } : value == Genre.Romance ? {
        Romance: null
    } : value == Genre.Thriller ? {
        Thriller: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PremiumPlan): {
    Monthly: null;
} | {
    Yearly: null;
} {
    return value == PremiumPlan.Monthly ? {
        Monthly: null
    } : value == PremiumPlan.Yearly ? {
        Yearly: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
